name: required labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - 'main'
jobs:
  state_compatability_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with: #Require one of the following labels
          mode: exactly
          count: 1
          labels: "V:state/breaking, V:state/compatible/no_backport, V:state/compatible/backport"
